general:
  projectName: 'jenkins-library'
  git:
    url: 'projectUrl'
    branch:

stage:
  build:
    maven:
      command: 'mvn clean package'
      args: '-DskipTests'

step:
  mainTest:
    url: 'testUrl'
    username: 'levine'
    password: '####'

post:
